### ISSUE TITLE
Switch to MakeMaker for better cross-compiling support

### ISSUE THREAD

**Issue by rehsack** [kazeburo/Cookie-Baker-XS#2]
Hi,

I maintain some perl module packages for Yocto (see meta-cpan) and realized that generally MakeMaker based distributions have much less problems in cross-compiling.

Since Cookie-Baker-XS is a recommendation by Cookie-Baker, I'd like to try it but I would seriously prefer easier compiler tuning by environment by overriding make paramaters instead of hacking into M::B internals.

Cheers,
Jens

**Comment by kazeburo** [comment]
How about Module::Build::Tiny?

**Comment by rehsack** [comment]
The problem is the lack of sane support of dynamic build environments.
Make supports such environments by design.

**Comment by kazeburo** [comment]
OK. just released v0.05.
Minilla already supports MakeMaker. I only added one line to minil.toml and moved XS files top directory.
Thank you for giving advice.

**Comment by rehsack** [comment]
Thanks, added it: https://github.com/rehsack/meta-cpan/commit/582bc4d467733a6951a28822ff31d9cefa98d61b
